"""Initial migration

Revision ID: 8cf3f2cd31c3
Revises: 
Create Date: 2024-07-14 18:05:13.929933

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '8cf3f2cd31c3'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('atletas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('cpf', sa.String(), nullable=True),
    sa.Column('centro_treinamento', sa.String(), nullable=True),
    sa.Column('categoria', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_atletas_cpf'), 'atletas', ['cpf'], unique=True)
    op.create_index(op.f('ix_atletas_id'), 'atletas', ['id'], unique=False)
    op.create_index(op.f('ix_atletas_nome'), 'atletas', ['nome'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_atletas_nome'), table_name='atletas')
    op.drop_index(op.f('ix_atletas_id'), table_name='atletas')
    op.drop_index(op.f('ix_atletas_cpf'), table_name='atletas')
    op.drop_table('atletas')
    # ### end Alembic commands ###
